### ISSUE TITLE
Bank 클래스의 register 매소드 작성하기

### ISSUE THREAD

**Issue by lalyns** [lalyns/bankapplication#5]
register(), manage(), search()의 매소드 기능을 작성합니다.

**Comment by ljwon1203** [comment]
계좌 등록하기 기능 추가 완료. 계좌번호 정규표현식으로 표현 함.
고민해볼 문제 : 계좌에 문자가 섞여있을 경우 문자가 입력된 경우 계좌생성 제한해야할 필요 있음.
